# Generated by Django 4.2.7 on 2023-12-11 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('primer_nombre', models.CharField(max_length=45)),
                ('segundo_nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('primer_apellido', models.CharField(max_length=45)),
                ('segundo_apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('correo', models.CharField(max_length=120, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=45, null=True)),
                ('fechanacimiento', models.DateField(blank=True, db_column='fechaNacimiento', null=True)),
                ('foto', models.CharField(blank=True, max_length=45, null=True)),
                ('n_identificacion', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'Usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categoriaservicio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'categoriaservicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('codigo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'departamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tdocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tdocumento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=160, null=True)),
                ('dueñp_taller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dueñp_taller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'taller',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('precio', models.CharField(max_length=45)),
                ('categoriaservicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.categoriaservicio')),
                ('id_taller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_taller', to='principal.taller')),
            ],
            options={
                'db_table': 'servicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Redessociales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tiporedsocial', models.CharField(db_column='tipoRedSocial', max_length=100)),
                ('enlaceredsocial', models.CharField(db_column='enlaceRedSocial', max_length=45)),
                ('taller_redsocial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='taller_redsocial', to='principal.taller')),
            ],
            options={
                'db_table': 'redessociales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=145)),
                ('body', models.CharField(db_column='body', max_length=145)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pagosuscripcion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipopago', models.CharField(blank=True, db_column='tipoPago', max_length=45, null=True)),
                ('usuario_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pagosuscripcion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('departamento_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departamento_id', to='principal.departamento')),
            ],
            options={
                'db_table': 'municipio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('fechacarga', models.DateField(blank=True, db_column='fechaCarga', null=True)),
                ('material_taller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='material_taller', to='principal.taller')),
            ],
            options={
                'db_table': 'materiales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=160)),
                ('puntuacion', models.DecimalField(decimal_places=0, max_digits=10)),
                ('ahutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ahutor', to=settings.AUTH_USER_MODEL)),
                ('reptor_taller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reptor_taller', to='principal.taller')),
            ],
            options={
                'db_table': 'comentarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lugar', models.CharField(blank=True, max_length=45, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('asunto', models.CharField(blank=True, max_length=160, null=True)),
                ('taller_reseptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='taller_reseptor', to='principal.taller')),
                ('usuario_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'citas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Archivosadjuntos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombrearchivo', models.CharField(db_column='nombreArchivo', max_length=145)),
                ('rutaarchivo', models.CharField(blank=True, db_column='rutaArchivo', max_length=145, null=True)),
                ('materiales_adjuntos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='materiales_adjuntos', to='principal.materiales')),
            ],
            options={
                'db_table': 'archivosadjuntos',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='municipio', to='principal.municipio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipodocumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipodocumento', to='principal.tdocumento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
