# Generated by Django 4.2.7 on 2023-12-02 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriaservicio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'categoriaservicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('codigo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'departamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.departamento')),
            ],
            options={
                'db_table': 'municipio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, max_length=45, null=True)),
                ('genero', models.CharField(blank=True, max_length=45, null=True)),
                ('fechanacimiento', models.DateField(blank=True, db_column='fechaNacimiento', null=True)),
                ('foto', models.CharField(blank=True, max_length=45, null=True)),
                ('contrato_id', models.IntegerField()),
                ('tpempresario_id', models.IntegerField()),
                ('idcedula', models.IntegerField(blank=True, null=True)),
                ('tipodocumento', models.CharField(blank=True, db_column='tipoDocumento', max_length=45, null=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.municipio')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=160, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.usuario')),
            ],
            options={
                'db_table': 'taller',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('precio', models.CharField(max_length=45)),
                ('categoriaservicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.categoriaservicio')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.taller')),
            ],
            options={
                'db_table': 'servicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Redessociales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tiporedsocial', models.CharField(db_column='tipoRedSocial', max_length=100)),
                ('enlaceredsocial', models.CharField(db_column='enlaceRedSocial', max_length=45)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.taller')),
            ],
            options={
                'db_table': 'redessociales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=145)),
                ('body', models.CharField(db_column='body', max_length=145)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Post',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pagosuscripcion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipopago', models.CharField(blank=True, db_column='tipoPago', max_length=45, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.usuario')),
            ],
            options={
                'db_table': 'pagosuscripcion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('fechacarga', models.DateField(blank=True, db_column='fechaCarga', null=True)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.taller')),
            ],
            options={
                'db_table': 'materiales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=160)),
                ('puntuacion', models.DecimalField(decimal_places=0, max_digits=10)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.taller')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.usuario')),
            ],
            options={
                'db_table': 'comentarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lugar', models.CharField(blank=True, max_length=45, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('asunto', models.CharField(blank=True, max_length=160, null=True)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.taller')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.usuario')),
            ],
            options={
                'db_table': 'citas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Archivosadjuntos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombrearchivo', models.CharField(db_column='nombreArchivo', max_length=145)),
                ('rutaarchivo', models.CharField(blank=True, db_column='rutaArchivo', max_length=145, null=True)),
                ('materiales', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.materiales')),
            ],
            options={
                'db_table': 'archivosadjuntos',
                'managed': True,
            },
        ),
    ]
